# Site settings
title: Joeybase
email: kangbj_at_gmail.com
description: Knowledge base focused on programming
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: N/A
github_username:  joeykang

# Disqus comments configuration
disqus_shortname: 'joeybase'

# Build settings
markdown: kramdown
sass:
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag