# Site settings
title: Online Bookmarks
email: kangbj_at_gmail.com
description: Knowledge base focused on programming
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: N/A
github_username:  joeykang

# Build settings
markdown: redcarpet
pygments: true
markdown_ext:  markdown,mkdown,mkdn,mkd,md
